name: ESLint Code Analysis

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Install ESLint SARIF Formatter
        run: npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: Verify installations
        run: |
          echo "ESLint version:"
          npx eslint --version
          echo "SARIF formatter check:"
          npm list @microsoft/eslint-formatter-sarif
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Test ESLint command first
        run: |
          echo "Testing basic ESLint:"
          npx eslint . --format stylish || echo "ESLint had issues"

      - name: Run ESLint with SARIF output
        run: |
          echo "Running ESLint with SARIF formatter..."
          npx eslint . --format @microsoft/eslint-formatter-sarif --output-file reports/eslint-results.sarif 2>&1
          echo "ESLint SARIF command exit code: $?"

      - name: Debug ESLint Output
        run: |
          echo "Checking reports directory:"
          ls -la reports/
          if [ -f reports/eslint-results.sarif ]; then
            echo "SARIF file found! Contents:"
            cat reports/eslint-results.sarif
          else
            echo "No SARIF report generated"
            echo "Creating minimal SARIF file:"
            echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"ESLint"}},"results":[]}]}' > reports/eslint-results.sarif
          fi

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/eslint-results.sarif
        continue-on-error: true
